---

- name: install pip
  apt: name=python-pip state=present

# required to prevent bug:
# https://github.com/ansible/ansible/issues/10810
- name: ensure pip is upgraded
  command: easy_install -U pip

# latest version of docker-py breaks all the things:
# https://github.com/ansible/ansible-modules-core/issues/1227
- name: install docker-py
  pip: name=docker-py version=1.1.0 state=present

- name: add docker apt key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: add docker apt repo
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: install lxc-docker
  apt: name=lxc-docker state=present

- name: restart docker service
  service: name=docker state=restarted

- name: make db directory
  file: path=/data/db state=directory

- name: make backup directory
  file: path=/data/backup state=directory

- name: docker mongo
  docker:
    name: mongo
    image: mongo:3
    volumes:
      - /data/db:/data/db
      - /data/backup:/data/backup

- name: docker java
  docker: 
    image: java:8
    state: present
